/**
 * SpreadShirtShop
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Colors
import org.openapitools.client.models.PrintType

import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param name 
 * @param colors 
 * @param printTypes 
 */

data class Appearance (

    @Json(name = "id")
    val id: kotlin.Int? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "colors")
    val colors: kotlin.collections.List<Colors>? = null,

    @Json(name = "printTypes")
    val printTypes: kotlin.collections.List<PrintType>? = null

)

