/**
 * SpreadShirtShop
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param plain 
 * @param isoCode 
 * @param symbol 
 * @param decimalCount 
 * @param pattern 
 * @param href 
 */

data class Currency (

    @Json(name = "id")
    val id: kotlin.Int? = null,

    @Json(name = "plain")
    val plain: kotlin.String? = null,

    @Json(name = "isoCode")
    val isoCode: kotlin.String? = null,

    @Json(name = "symbol")
    val symbol: kotlin.String? = null,

    @Json(name = "decimalCount")
    val decimalCount: kotlin.Double? = null,

    @Json(name = "pattern")
    val pattern: kotlin.String? = null,

    @Json(name = "href")
    val href: kotlin.String? = null

)

