/**
 * SpreadShirtShop
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Currency

import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param currency 
 * @param amount 
 * @param currencyIdRaw 
 */

data class CurrencyPrice (

    @Json(name = "id")
    val id: kotlin.Int? = null,

    @Json(name = "currency")
    val currency: Currency? = null,

    @Json(name = "amount")
    val amount: kotlin.Double? = null,

    @Json(name = "currencyIdRaw")
    val currencyIdRaw: kotlin.Int? = null

)

