/**
 * SpreadShirtShop
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Currency

import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param vatExcluded 
 * @param vatIncluded 
 * @param vat 
 * @param currency 
 */

data class ProductTypePrice (

    @Json(name = "id")
    val id: kotlin.Int? = null,

    @Json(name = "vatExcluded")
    val vatExcluded: kotlin.Double? = null,

    @Json(name = "vatIncluded")
    val vatIncluded: kotlin.Double? = null,

    @Json(name = "vat")
    val vat: kotlin.Double? = null,

    @Json(name = "currency")
    val currency: Currency? = null

)

