/**
 * SpreadShirtShop
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Appearance
import org.openapitools.client.models.ProductTypePrice
import org.openapitools.client.models.Sellable
import org.openapitools.client.models.ShippingCountry
import org.openapitools.client.models.Size
import org.openapitools.client.models.StockState
import org.openapitools.client.models.WashingInstruction

import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param href 
 * @param name 
 * @param description 
 * @param shortDescription 
 * @param categoryName 
 * @param weight 
 * @param brand 
 * @param shippingFactor 
 * @param sizeFitHint 
 * @param customsTariffCode 
 * @param manufacturingCountry 
 * @param price 
 * @param appearances 
 * @param sizes 
 * @param washingInstructions 
 * @param stockStates 
 * @param giftWrappingSupported 
 * @param sellables 
 */

data class ProductType (

    @Json(name = "id")
    val id: kotlin.Int? = null,

    @Json(name = "href")
    val href: kotlin.String? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "shortDescription")
    val shortDescription: kotlin.String? = null,

    @Json(name = "categoryName")
    val categoryName: kotlin.String? = null,

    @Json(name = "weight")
    val weight: kotlin.Double? = null,

    @Json(name = "brand")
    val brand: kotlin.String? = null,

    @Json(name = "shippingFactor")
    val shippingFactor: kotlin.Double? = null,

    @Json(name = "sizeFitHint")
    val sizeFitHint: kotlin.String? = null,

    @Json(name = "customsTariffCode")
    val customsTariffCode: kotlin.String? = null,

    @Json(name = "manufacturingCountry")
    val manufacturingCountry: ShippingCountry? = null,

    @Json(name = "price")
    val price: ProductTypePrice? = null,

    @Json(name = "appearances")
    val appearances: kotlin.collections.List<Appearance>? = null,

    @Json(name = "sizes")
    val sizes: kotlin.collections.List<Size>? = null,

    @Json(name = "washingInstructions")
    val washingInstructions: kotlin.collections.List<WashingInstruction>? = null,

    @Json(name = "stockStates")
    val stockStates: kotlin.collections.List<StockState>? = null,

    @Json(name = "giftWrappingSupported")
    val giftWrappingSupported: kotlin.Boolean? = null,

    @Json(name = "sellables")
    val sellables: kotlin.collections.List<Sellable>? = null

)

