/**
 * SpreadShirtShop
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Appearance
import org.openapitools.client.models.CurrencyPrice
import org.openapitools.client.models.ImageModel
import org.openapitools.client.models.ProductType
import org.openapitools.client.models.Tag

import com.squareup.moshi.Json

/**
 * 
 *
 * @param sellableId 
 * @param ideaId 
 * @param mainDesignId 
 * @param productType 
 * @param tags 
 * @param price 
 * @param previewImage 
 * @param appearances 
 * @param defaultAppearanceId 
 */

data class Sellable (

    @Json(name = "sellableId")
    val sellableId: kotlin.String? = null,

    @Json(name = "ideaId")
    val ideaId: kotlin.String? = null,

    @Json(name = "mainDesignId")
    val mainDesignId: kotlin.String? = null,

    @Json(name = "productType")
    val productType: ProductType? = null,

    @Json(name = "tags")
    val tags: kotlin.collections.List<Tag>? = null,

    @Json(name = "price")
    val price: CurrencyPrice? = null,

    @Json(name = "previewImage")
    val previewImage: ImageModel? = null,

    @Json(name = "appearances")
    val appearances: kotlin.collections.List<Appearance>? = null,

    @Json(name = "defaultAppearanceId")
    val defaultAppearanceId: kotlin.Int? = null

)

