/**
 * SpreadShirtShop
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Appearance
import org.openapitools.client.models.Size

import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param appearance 
 * @param propertySize 
 * @param available 
 * @param quantity 
 */

data class StockState (

    @Json(name = "id")
    val id: kotlin.Int? = null,

    @Json(name = "appearance")
    val appearance: Appearance? = null,

    @Json(name = "size")
    val propertySize: Size? = null,

    @Json(name = "available")
    val available: kotlin.Boolean? = null,

    @Json(name = "quantity")
    val quantity: kotlin.Int? = null

)

